import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, test } from '@jest/globals';

import { createConversationDb, SqliteThreadRepository } from '../src/conversation/repositories/SqliteRepositories';
import { ConversationResultSetRepository } from '../src/resultSets/ConversationResultSetRepository';

describe('ConversationResultSetRepository',()=>{
  test('resolves ordinals with generic context and metadata, then cascades with thread deletion',async()=>{const db=createConversationDb(':memory:');const threads=new SqliteThreadRepository(db);await threads.getOrCreate('thread-culture');const repository=new ConversationResultSetRepository(db);repository.create({threadId:'thread-culture',sourceAgent:'culture',sourceAction:'discover',context:{latitude:48.85,longitude:2.35,radiusKm:15,from:'2026-08-27T00:00:00.000Z',to:'2026-08-28T00:00:00.000Z'},items:[{entityType:'agora.item',entityId:'item_1',displayLabel:'Premier film'},{entityType:'agora.occurrence',entityId:'occ_2',displayLabel:'Deuxième séance',metadata:{candidate:{id:'candidate_2'}}}]});const second=repository.resolveReference('thread-culture','le deuxième');expect(second).toMatchObject({entityType:'agora.occurrence',entityId:'occ_2',metadata:{candidate:{id:'candidate_2'}},resultSetContext:{latitude:48.85,radiusKm:15}});expect(repository.resolveReference('thread-culture','et lui ?')?.entityId).toBe('occ_2');await threads.deleteThread('thread-culture');expect(repository.findActive('thread-culture')).toBeNull();db.close();});

  test('keeps only the newest set active for a thread',async()=>{const db=createConversationDb(':memory:');const threads=new SqliteThreadRepository(db);await threads.getOrCreate('thread-newest');const repository=new ConversationResultSetRepository(db);repository.create({threadId:'thread-newest',sourceAgent:'search',sourceAction:'query',items:[{entityType:'search.result',entityId:'old',displayLabel:'Ancien'}]});repository.create({threadId:'thread-newest',sourceAgent:'culture',sourceAction:'discover',items:[{entityType:'agora.item',entityId:'new',displayLabel:'Nouveau'}]});expect(repository.resolveReference('thread-newest','le premier')?.entityId).toBe('new');db.close();});

  test('adds generic context columns to an existing ResultSet database without dropping data',()=>{const directory=mkdtempSync(join(tmpdir(),'jarvis-resultset-migration-'));const path=join(directory,'conversation.sqlite');const legacy=createConversationDb(path);legacy.exec("INSERT INTO conversation_threads(thread_id,created_at_ms,updated_at_ms) VALUES('legacy-thread',1,1)");legacy.exec("INSERT INTO conversation_result_sets(id,thread_id,source_agent,source_action,created_at_ms,expires_at_ms,active) VALUES('legacy-set','legacy-thread','search','query',1,9999999999999,1)");legacy.exec("INSERT INTO conversation_result_set_items(result_set_id,position,entity_type,entity_id,display_label) VALUES('legacy-set',1,'search.result','legacy-item','Ancien résultat')");legacy.exec('ALTER TABLE conversation_result_set_items DROP COLUMN metadata_json');legacy.exec('ALTER TABLE conversation_result_sets DROP COLUMN context_json');legacy.close();const migrated=createConversationDb(path);const repository=new ConversationResultSetRepository(migrated);expect(repository.findActive('legacy-thread')?.items[0]).toMatchObject({entityId:'legacy-item',metadata:null});expect(repository.findActive('legacy-thread')?.context).toBeNull();migrated.close();rmSync(directory,{recursive:true,force:true});});
});
